# Generated by Django 3.2.4 on 2021-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('opens_at', models.CharField(max_length=100)),
                ('closes_at', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('photo', models.ImageField(blank=True, default='profile/default_user.jpg', upload_to='profile/default_pharmacy.jpg')),
            ],
        ),
    ]
