# Generated by Django 3.2.4 on 2021-07-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='first_name',
            new_name='pharmacy_name',
        ),
    ]
