# Generated by Django 3.2.4 on 2021-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reply_note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
