# Generated by Django 3.2.4 on 2021-07-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210710_1138'),
        ('appointment', '0003_alter_appointment_reply_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.patient'),
        ),
    ]
