# Generated by Django 3.2.4 on 2021-07-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210710_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
