# Generated by Django 3.2.4 on 2021-07-10 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_doctor_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 10, 13, 7, 29, 622595, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
