# Generated by Django 3.2.4 on 2021-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_remark',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reply_note',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
