# Generated by Django 3.2.4 on 2021-07-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20210712_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_remark',
        ),
    ]
