# Generated by Django 3.2.4 on 2021-07-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_appointment',
        ),
    ]
