# Generated by Django 3.2.4 on 2021-07-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_status'),
        ('accounts', '0003_auto_20210707_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
            preserve_default=False,
        ),
    ]
