# Generated by Django 3.2.4 on 2021-07-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210710_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_appointment',
        ),
    ]
