# Generated by Django 3.2.4 on 2021-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210710_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='prabesh-pathak-1', unique=True),
            preserve_default=False,
        ),
    ]
