# Generated by Django 3.2.4 on 2021-07-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210716_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='fromYear1',
            new_name='from_year1',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='toYear1',
            new_name='to_year1',
        ),
    ]
