# Generated by Django 3.2.4 on 2021-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210716_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='place_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='place_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
