# Generated by Django 3.2.4 on 2021-07-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctorprofile_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='services',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
