# Generated by Django 3.2.4 on 2021-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctorprofile_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
